version: "3.8"
services:
  arma:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-arma
    tty: true
    ports:
      - "3000:3000"  
    volumes:
      - ./:/app  
    develop:
      watch:
        - action: sync
          path: ./
          target: ./app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
